### ISSUE TITLE
Create docker with the Issuer

### ISSUE THREAD

**Issue by pinamiranda** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#20]
Would be easier to install and test the Issuer.

**Comment by bjornmolin** [comment]
Is there any work on this?

We have made a Dockerfile to build an image to be able to deploy on k8s. We could contribute with it in a PR. However, we consider it important in that case to handle configuration in a different way. Suggesting the way we usually work in #49

**Comment by pinamiranda** [comment]
It will be added to v. 0.6.0
