### ISSUE TITLE
Update version to draft 13

### ISSUE THREAD

**Issue by YasserHawass** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#23]
Currently the Android UI is working with draft 13 according to 
[Error on Android EUDI app clicking new National ID #91](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/91)

and works with backend https://dev.issuer.eudiw.dev. However, the current repo are not up-to-date with it.

for example: when calling https://dev.issuer.eudiw.dev/.well-known/openid-credential-issuer vs localhost/oidc/.well-known/openid-credential-issuer we recieve different responses, which determine the flow of the application.
![image](https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py/assets/24258684/fa06b48d-6401-4499-9e16-da1e02e29d1f)

Is it possible to have the latest version working with current implementations of Android Studio?

**Comment by Wonko-42** [comment]
I'm having the same issue, let me know if you manage to resolve it

**Comment by elblasto420** [comment]
Hi all. I have the same issue, when we use the Python Issuer we only get to the first endpoint, https://issuer.eudiw.dev/oidc/.well-known/openid-credential-issuer
![image](https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py/assets/22560149/cb86f007-9892-472f-89e4-0b71a9871e88)
Afterwards I get the following error on Android:
![image](https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py/assets/22560149/ceccb66d-fe37-47ad-855b-27d5ce29c567)
To be noted, this happens with the latest version (13) but this has also been happening with previous versions. However when I switch to the Kotlin Issuer (let us remember Python is the Demo Flavor and Kotlin is the Dev Flavor) it works perfectly fine as of the latest version. Regardless if you use their Issuer or you raise your own, you'll get the same error. Can anyone look into it?

**Comment by pinamiranda** [comment]
Hi @YasserHawass , 

Thank you for open this issue.

> Currently the Android UI is working with draft 13 according to [Error on Android EUDI app clicking new National ID #91](https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/91)
> 
> and works with backend https://dev.issuer.eudiw.dev. However, the current repo are not up-to-date with it.
> 

This repo is up-to-date with the https://issuer.eudiw.dev backend., and we have published today the EUDIW Issuer that supports OID4VCI draft 13.
