### ISSUE TITLE
Credential Offer

### ISSUE THREAD

**Issue by Nieuwlaar** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#34]
Hi,

It is great to see the progress of the NiScy wallet, thank you for that!

I have managed to set up the Python issuer locally (as it is equally looking as the https://issuer.eudiw.dev/ ). However, I am wondering how I could create a credential offer to actually issue a credential (like https://issuer-backend.eudiw.dev/)?

Any direction is appreciated!

**Comment by LuisPereira23** [comment]
Hello @Nieuwlaar 

We're excited to see you trying out our issuer!

For helpful information on your issue, please refer to our documentation here:
[Credential Offer](https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py/blob/main/api_docs/credential_offer.md)

**Comment by pinamiranda** [comment]
Closed due to inactivity. If necessary, please reopen.
