### ISSUE TITLE
Hardcoded references to verifier backend

### ISSUE THREAD

**Issue by potential-nl-blsp** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#44]
The code, specifically in app/route_oidc.py and app/route_oid4vp.py contains hardcoded references to the verifier backend (dev.verifier-backend.eudiw.dev) at NiScy. Because of this, the code "as is" cannot be used in  a completely seperate deployment (i.e. with own instance of verifier backend).

This is a request to make the verifier backend to be used configurable.

**Comment by pinamiranda** [comment]
Thank you for your request. It will be added in the next version.
