### ISSUE TITLE
Oups! Something went wrong. If the issue persists, please contact customer

### ISSUE THREAD

**Issue by AlessandroFerrara00** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#46]
I installed the EUDIW ISSUER app locally and made sure it also ran over HTTPS.
Of course, I followed the whole configuration:
https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py/blob/main/api_docs/configuration.md
Then I modified the required files, setting ‘localhost’ instead of ‘issuer.eudiw.dev’.
Having done that, I also followed the guide to add a new credential, and indeed when I run the app locally, the new credential is there.
Now, when I choose the credential to be issued in the app, why, when I scan the QR Code with my mobile device, does the app give me the error ‘Oups! Something went wrong. If the issue persists, please contact customer’?

PS: as a test I tried changing the uri in the ‘route_oidc’ file by setting it to: f ‘openid-credential-offer://credential_offer/?credential_offer=%7B%22credential_issuer%22:%20%22https://192.168.1.199:5000%22%2C%20%22credential_configuration_ids%22:%20%5B%22eu.europa.ec.eudi.loyalty_mdoc%22%5D%2C%20%22grants%22:%20%7B%22authorization_code%22:%20%7B%7D%7D%7D’
I know that this way, the document to be issued, whichever way you choose, should always be ‘loyalty_mdoc’, but I did it statically just to try it out, however it doesn't work because I think there is a problem with the credential_issuer.
So I'm wondering if I'm working correctly, can anyone help me?

**Comment by Paul2708** [comment]
The following works for me:

- Replace _any_ occurrence of "issuer.eudiw.dev" with a ngrok URL pointing to port 5000 (HTTP)
- Use format "mso_mdoc" because SD-JWT is currently not supported for the Android app (see https://github.com/eu-digital-identity-wallet/eudi-app-android-wallet-ui/issues/148#issuecomment-2253045595)
- Add `demo.json` into the directory `credentials_supported`: 
[demo.json](https://github.com/user-attachments/files/16838044/demo.json)

- Apply the following code changes:

**config_countries.py (supported_countries)**

```python
formCountry: {
            "name": "FormEU",
            "pid_url": cfgserv.service_url + "pid/form",
            "pid_mdoc_privkey": "/home/paul/temp/eudi-srv-web-issuing-eudiw-py/app/private/ds_token/PID-DS-0002.pid-ds-0002.key.pem", # Replace with your key path
            # "pid_mdoc_privkey": 'app\certs\PID-DS-0001_UT.pem',
            "pid_mdoc_privkey_passwd": b"pid-ds-0002",  # None or bytes
            "pid_mdoc_cert": "/home/paul/
temp/eudi-srv-web-issuing-eudiw-py/app/private/ds_token/PID-DS-0002.cert.der", # Replace with your key path
            "un_distinguishing_sign": "FC",
            "supported_credentials": [
                "eu.europa.ec.eudi.pid_mdoc",
                "eu.europa.ec.eudi.pid_jwt_vc_json",
                "eu.europa.ec.eudi.mdl_jwt_vc_json",
                "eu.europa.ec.eudi.mdl_mdoc",
                "eu.europa.ec.eudi.over18_mdoc",
                "eu.europa.ec.eudi.loyalty_mdoc",
                "eu.europa.ec.eudi.pseudonym_over18_mdoc",
                "eu.europa.ec.eudi.pseudonym_over18_mdoc_deferred_endpoint",
                "demo"
            ],
            "dynamic_R2": cfgserv.service_url + "dynamic/form_R2",
        },
```

**config_service.py**

```python
auth_method_supported_credencials = {
        "PID_login": [
            "eu.europa.ec.eudi.pseudonym_over18_mdoc",
            "eu.europa.ec.eudi.pseudonym_over18_mdoc_deferred_endpoint",
        ],
        "country_selection": [
            "eu.europa.ec.eudi.loyalty_mdoc",
            "eu.europa.ec.eudi.mdl_jwt_vc_json",
            "eu.europa.ec.eudi.mdl_mdoc",
            "eu.europa.ec.eudi.pid_jwt_vc_json",
            "eu.europa.ec.eudi.pid_mdoc",
            "eu.europa.ec.eudi.pseudonym_over18_mdoc",
            "eu.europa.ec.eudi.pseudonym_over18_mdoc_deferred_endpoint",
            "eu.europa.ec.eudi.photoid",
            "demo"
        ],
    }
```

Using this setup, the website shows "demo," and I can successfully issue to my EUDI Wallet.
Currently, I struggle to set custom claims because I do not understand the relation between namespace, doctype, scope, and claims yet.
