### ISSUE TITLE
Cannot run issuer due to conflicting dependencies

### ISSUE THREAD

**Issue by potential-nl-blsp** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#48]
Issuer does not run anymore because of conflicting dependencies due to an update to fedservice a few days ago:

```
INFO: pip is looking at multiple versions of fedservice to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r app/requirements.txt (line 27), -r app/requirements.txt (line 29) and idpyoidc 4.3.0 (from git+https://github.com/eu-digital-identity-wallet/idpy-oidc.git) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested idpyoidc 4.3.0 (from git+https://github.com/eu-digital-identity-wallet/idpy-oidc.git)
    openid4v 0.1.0 depends on idpyoidc>=4.0.0
    fedservice 5.1.0 depends on idpyoidc>=5.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by potential-nl-blsp** [comment]
Workaround: making the dependency on fedservice specific to the version prior to the update allows for running the issuer. Haven't done extensive testing though.

In app/requirements.txt add the commit version to the line for fedservice:
```
git+https://github.com/rohe/fedservice.git**@a6a2e1a**
```

**Comment by bjornmolin** [comment]
I have the same issue. Thanks for the suggested work-around.

**Comment by gfour** [comment]
A more recent fedservice that also seems to work is `67eaaed` (also, extensive testing not yet done).

**Comment by LuisPereira23** [comment]
@potential-nl-blsp @bjornmolin @gfour 
I would recommend:
`git+https://github.com/rohe/fedservice.git@a4bef2e3f230f4b07c6ef45e4c8be55778d0561e`
It is the version currently running on https://issuer.eudiw.dev/ and has been tested with.

**Comment by pinamiranda** [comment]
The dependencies will be updated in the next Issuer version.
