### ISSUE TITLE
config with environment variables

### ISSUE THREAD

**Issue by bjornmolin** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#49]
I would like to suggest doing configuration with environment variables instead of in source code. It makes it easier to build containers and during deployment set configuration with e.g. config maps and sealed secrets on k8s. Furthermore, in that way it becomes easier to build a container that does not contain anything secret.

For local development you can also use dotenv so you can have a file locally for the configuration. Preferably a template for it in the code repo

When the content is large, you can enter a path in the config environment variable and then you can mount a file with the content on that path.

All so as not to accidentally insert secrets or customizations into the container image.

**Comment by janderssonse** [comment]
+1
