### ISSUE TITLE
Local /credential response object differs from issuer.eudiw.dev /credential one

### ISSUE THREAD

**Issue by Simmi** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#50]
This is more of a question than an issue I suspect.

I've got the server running locally using ngrok, and it seems to work fine. 
Using my EUDI wallet I've been issuing Pseudonym credentials to it from the EUDI service and it works, where the credential coming from https://issuer.eudiw.dev/credential gives me a credential of the form:

`{
    "issuerAuth": [...]
 }`
 But the same issuance (Pseudonym) locally gives me a credential that is 'higher up' in the JSON:
 
 `{
 "status": 0,
"version": "1.0",
"documents": [
    {
        "docType":"eu.europa.ec.eudi.pseudonym.age_over_18.1",
        "issuerSigned": {
            "issuerAuth": [...]
        }
    }
}`

And since the wallet expects there to be a `issuerAuth` as first child of the response I get an error (the Android/Kotlin line that fails is: `val issuerAuthBytes = issuerSigned["issuerAuth"].EncodeToBytes().` from within `DocumentManagerImpl.kt`)

Does anyone know why this might be happening?

**Comment by LuisPereira23** [comment]
Good afternoon @Simmi . This was a change implemented more than 3 months ago in the pyMDOC-CBOR dependency for the issuer. 
Please make sure the following requirement is up to date in your local instance by running 
`pip install git+https://github.com/eu-digital-identity-wallet/pyMDOC-CBOR.git`

**Comment by Simmi** [comment]
Thank you very much @LuisPereira23, I'll verify this as soon as I can 🤞🏻

**Comment by Simmi** [comment]
Could it then be @LuisPereira23 that the formatter_func.py isn't up to date with this new version of pyMDOC-CBOR?

I'm getting some errors related to a change to the MdocCborIssuer constructor (looks like there has been change to the arguments needed for construction)
