### ISSUE TITLE
External Authorization Server Support

### ISSUE THREAD

**Issue by dariocast** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#51]
Is there any way to integrate an existing authorization server (as with the kotlin version of the pid-issuer)?

**Comment by mgiakkou** [comment]
Dear Dario,

Thank you for your point. Unfortunately, the implementation that you mention is not currently in the development priorities, but please stay tuned in [here[\](https://github.com/orgs/eu-digital-identity-wallet/projects/24) where you will be able to see the future developments planned.

Thank you,
Michalis.
