### ISSUE TITLE
Estonian test PID not working

### ISSUE THREAD

**Issue by EneliKirme** [eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py#9]
While adding document in EUDI Wallet and choosing National ID, issuing PID from Estonia is not working. In case of choosing Smart-ID or Mobile-ID for authentication, both return an error messages.

**Comment by pinamiranda** [comment]
Hi @EneliKirme ,

The test PID Provider (https://issuer.eudiw.dev/) is integrated with the Estonian Identity Provider pre-production/test environment. To issue an Estonian test PID, you must use a testing account. For further details, please refer to https://e-gov.github.io/TARA-Doku/Testing#21-quick-reference-of-testing-accounts. 

If you're installing the [eudi-srv-web-issuing-eudiw-py](https://github.com/eu-digital-identity-wallet/eudi-srv-web-issuing-eudiw-py), you will need to to first [submit an application to join the TARA test environment](https://e-gov.github.io/TARA-Doku/Liitumine), and configure the "pid_url_oidc" in the eudi-srv-web-issuing-eudiw-py/app/app_config/config_countries.py file.

Thank you for your comment

**Comment by pinamiranda** [comment]
Comment closed due to inactivity. If further feedback is required, the comment can be reopened.
